const RAW_DATA = {
  B: {
    name: "BASE CABINET",
    type_code: ["width"],
    width: [9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 42],
    height: [34.5],
    depth: [24],
    detail: {
      no_drawer: { drawer: 0, door: 1, type_suffix: "F", width: [9] },
      single_drawer: { drawer: 1, door: 1, name_suffix: " - SINGLE DOOR", width: [12, 15, 18, 21] },
      double_door: { drawer: 1, door: 2, name_suffix: " - DOUBLE DOOR", width: [24, 27, 30, 33, 36] },
      double_drawer: { drawer: 2, door: 2, name_suffix: " - DOUBLE DOOR", width: [42] },
    },
  },
  DB: {
    name: "DRAWER BASE CABINET",
    type_code: ["width"],
    width: [12, 15, 18, 21, 24, 27, 30, 33, 36],
    height: [34.5],
    depth: [24],
    variant: {
      double_drawer: { drawer: 2, type_suffix: "-2", allow_variant: { width: [24, 30, 36] } },
      triple_drawer: { drawer: 3 },
    },
  },
  BMC: {
    name: "BASE MICROWAVE CABINET",
    type_code: ["width"],
    width: [30, 27],
    height: [34.5],
    depth: [24],
  },
  DKD: {
    name: "DESK KNEE DREWER",
    type_code: ["width"],
    width: [30, 36],
    height: [6.625],
    depth: [21],
    detail: {
      out_width_30: { self_width: 24, width: [30] },
      out_width_36: { self_width: 30, width: [36] },
    },
  },
  BLS: {
    name: "BASE CORNER CABINET-LASY SUSAN",
    type_code: ["width"],
    width: [33, 36],
    height: [34.5],
    depth: [24],
  },
  BBC: {
    name: "BASE BLIND CORNER CABINET",
    type_code: ["width"],
    width: [36, 39, 42],
    height: [34.5],
    depth: [24],
    detail: {
      install_range_36: { install_range: 39, type_suffix: "39", width: [36] },
      install_range_39: { install_range: 42, type_suffix: "42", width: [39] },
      install_range_42: { install_range: 45, type_suffix: "45", width: [42] },
    },
  },
  BSR: {
    name: "BASE SPICE RACK CABINET",
    type_code: ["width"],
    width: [6, 9, 12],
    height: [34.5],
    depth: [24],
  },
  BES: {
    name: "BASE ENDING SHELF",
    type_code: ["width"],
    width: [9],
    height: [30],
    depth: [24],
  },
  RD: {
    name: "ROLL-OUT DRAWER",
    type_code: ["width"],
    width: [18, 21, 24, 27, 30, 33, 36],
    depth: [20.375],
  },
  SB: {
    name: "SINK BASE CABINET",
    type_code: ["width"],
    width: [30, 33, 36, 42],
    height: [34.5],
    depth: [24],
    detail: {
      single_fake_drawer: { fake_drawer: 1, door: 2, width: [30, 33, 36] },
      double_fake_drawer: { fake_drawer: 2, door: 2, width: [42] },
    },
  },
  FSB: {
    name: "FARMHOUSE SINK BASE",
    type_code: ["width"],
    width: [36],
    height: [34.5],
    depth: [24],
  },
  CSB: {
    name: "CORNER SINK",
    type_code: ["width"],
    width: [42],
    height: [34.5],
    depth: [24],
  },
  W: {
    name: "WALL CABINET",
    type_code: ["width", "height"],
    width: [9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 42],
    height: [12, 15, 18, 21, 24, 30, 36, 42],
    depth: [12, 24],
    detail: {
      single_door: { door: 1, name_suffix: " - SINGLE DOOR", width: [9, 12, 15, 18, 21] },
      double_door: { door: 2, name_suffix: " - DOUBLE DOOR", width: [24, 27, 30, 33, 36, 42] },
      double_shelves: { shelves: 2, height: [30, 36] },
      triple_shelves: { shelves: 3, height: [42] },
      not_wall_cab: { not_exist: true, width: [9, 12, 15, 18, 21, 24, 27, 33, 42], height: [18, 21, 24] },
      stackable: { name: "WALL STACKABLE CABINET", height: [12, 15], depth: [12] },
      not_stackable: { not_exist: true, width: [33, 42], height: [12, 15], depth: [12] },
      fridge: { name: "WALL FRIDGE CABINET", width: [30, 36], height: [12, 15, 18, 21, 24], depth: [24] },
      not_fridge_width: { not_exist: true, width: [9, 12, 15, 18, 21, 24, 27, 33, 42], depth: [24] },
      not_fridge_height: { not_exist: true, height: [30, 36, 42], depth: [24] },
      bridge: { name: "WALL BRIDGE CABINET", width: [30, 36], height: [12, 15, 18, 21, 24], depth: [12] },
    },
  },
  WDC: {
    name: "WALL DIAGONAL CORNER CABINET",
    type_code: ["width", "height"],
    width: [24],
    height: [15, 30, 36, 42],
    depth: [12],
  },
  WER: {
    name: "WALL EASYREACH CORNER CABINET",
    type_code: ["width", "height"],
    width: [24],
    height: [30, 36, 42],
    depth: [24],
  },
  WBC: {
    name: "WALL EASYREACH CORNER CABINET",
    type_code: ["width", "height"],
    width: [27],
    height: [30, 36, 42],
    depth: [12],
  },
  WES: {
    name: "WALL ENDING SHELF",
    type_code: ["width", "height"],
    width: [9],
    height: [30, 36, 42],
    depth: [12],
  },
  WMC: {
    name: "WALL MICROWAVE CABINET",
    type_code: ["width", "height"],
    width: [30, 27],
    height: [30, 36, 42],
    depth: [12],
  },
  WRC: {
    name: "WALL RACK",
    type_code: ["width", "height"],
    width: [30],
    height: [15],
    depth: [12],
  },
  PR: {
    name: "PLATE RACK",
    type_code: ["width", "height"],
    width: [30],
    height: [15],
    depth: [12],
  },
  UT: {
    name: "PANTRY",
    type_code: ["width", "height", "depth"],
    width: [18, 24, 36],
    height: [30, 36, 42, 51, 54],
    depth: [24],
    detail: {
      single_door: { door: 1, width: [18] },
      double_door: { door: 2, name_suffix: " CABINET", width: [24, 30, 36] },
      stack_top: { stack: "top", height: [30, 36, 42] },
      stack_bottom: { stack: "bottom", height: [51, 54] },
    },
  },
  OV: {
    name: "OVEN CABINET",
    type_code: ["width", "height", "depth"],
    width: [33],
    height: [15, 18, 21, 24, 27, 30, 66],
    depth: [24],
    detail: {
      stack_top: { stack: "top", height: [15, 18, 21, 24, 27, 30] },
      stack_bottom: { stack: "bottom", height: [66] },
    },
  },
  VDB: {
    name: "VANITY DRAWER BASE CABINET",
    type_code: ["width"],
    width: [12, 15, 18, 21, 24],
    height: [34.5],
    depth: [21],
  },
  VSB: {
    name: "VANITY SINK BASE CABINET",
    type_code: ["width"],
    width: [24, 27, 30, 36],
    height: [34.5],
    depth: [21],
    detail: {
      real_drawer: { drawer: 0, fake_drawer: 1 },
    },
  },
  VSD: {
    name: "VANITY SINK BASE CABINET",
    type_code: ["width"],
    width: [24, 27, 30, 36],
    height: [34.5],
    depth: [21],
    detail: {
      real_drawer: { drawer: 1, fake_drawer: 0 },
    },
  },
  VC: {
    name: "VANITY COMBINATION CABINET",
    type_code: ["width"],
    width: [30, 36, 42, 48],
    height: [34.5],
    depth: [21],
    variant: {
      left: { direction: "left", type_suffix: "L" },
      right: { direction: "right", type_suffix: "R" },
    },
    detail: {
      single_door: { door: 1, drawer: 2, fake_drawer: 1, width: [30] },
      double_door: { door: 2, drawer: 2, fake_drawer: 1, width: [36] },
      triple_drawer: { door: 2, drawer: 3, fake_drawer: 1, width: [42] },
      six_drawer: { door: 2, drawer: 6, fake_drawer: 1, width: [48] },
    },
  },
  BF: {
    name: "BASE FILLER",
    type_code: ["width"],
    width: [3, 6],
    height: [34.5],
    thickness: [1],
  },
  WF: {
    name: "WALL FILLER",
    type_code: ["width"],
    width: [3, 6],
    length: [42],
    thickness: [0.75],
  },
  TF: {
    name: "TALL FILLER",
    type_code: ["width"],
    width: [3, 6, 1.5],
    length: [96],
    thickness: [0.75],
    detail: {
      alias: { type: "RF", width: [1.5] },
    },
  },
  TK8: {
    name: "TOE KICK",
    width: [4.5],
    length: [96],
    thickness: [0.25],
  },
  PNL: {
    name: "PANEL",
    type_code: ["width", "length"],
    width: [24, 36, 39],
    length: [96],
    thickness: [0.25, 0.5, 0.75],
    detail: {
      alias: { type: "SK", width: [24], thickness: [0.25] },
      half_thick: { type_suffix: "H", thickness: [0.5] },
      quarter_thick: { type_suffix: "Q", thickness: [0.25] },
      not_3q: { not_exist: true, width: [24, 36], thickness: [0.75]},
      triple_quarter_thick: { type_suffix: "-3/4''", thickness: [0.75] },
      not_q: { not_exist: true, width: [39], thickness: [0.25, 0.5]},
    },
  },
  VAL: {
    name: "VALANCE",
    type_code: ["width"],
    width: [60],
  },
  LM8: {
    name: "LIGHT MOLDING",
    length: [96],
    variant: {
      l_shape: { shape: "L", type_suffix: "-L" },
      normal: { shape: "normal" },
    },
  },
  SM8: {
    name: "SCRIKE MOLDING",
    length: [96],
  },
  OSM8: {
    name: "OUTSIDE SCRIKE MOLDING",
    length: [96],
  },
  CM: {
    name: "CROWN MOLDING",
    width: [2.5, 3.4375, 4.375],
    length: [96],
    detail: {
      suffix_1: { type_suffix: "1-1/4", width: [2.5] },
      suffix_2: { type_suffix: "2-1/2", width: [3.4375] },
      suffix_4: { type_suffix: "4", width: [4.375] },
    },
  },
  CP: {
    name: "POST",
    type_code: ["width", "height"],
    width: [3],
    height: [34],
  },
  ACM8: {
    name: "ANGLED CROWN MOLDING",
    length: [96],
  },
  CCM: {
    name: "COUE CROWN MOLDING",
    width: [2.5, 5],
    length: [96],
    detail: {
      suffix_2: { type_suffix: "2-1/2", width: [2.5] },
      suffix_5: { type_suffix: "5", width: [5] },
    },
  },
  CBL: {
    name: "CORBEL",
  },
  WDD: {
    name: "DECOR DOOR",
    type_code: ["width", "height"],
    width: [12],
    height: [30, 36, 42],
  },
  BDD: {
    name: "DECOR DOOR",
    type_code: ["width"],
    width: [24],
    height: [30],
  },
  VDD: {
    name: "DECOR DOOR",
    type_code: ["width"],
    width: [21],
    height: [30],
  },
  QR8: {
    name: "QUARTER ROUND",
    length: [96],
  },
  GH: {
    name: "GLASS HOLDER",
    type_code: ["width"],
    width: [30],
  },
  BM8: {
    name: "FANCY TOE KICK",
    width: [4.5],
    length: [96],
    thickness: [0.75],
  },
  BEP: {
    name: "BASE ENDING PANEL",
    type_code: ["width"],
    width: [24],
    height: [30],
  },
  WEP: {
    name: "WALL ENDING PANEL",
    type_code: ["width", "height"],
    width: [12],
    height: [30, 36, 42],
  },
  SD: {
    name: "SAMPLE DOOR",
    width: [12],
    height: [15],
  },
};